name: Build and deploy Doxygen documentation

on:
  push:
    branches: main
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - uses: mattnotmitt/doxygen-action@v1.9.5
    - uses : peaceiris/actions-gh-pages